notifications:
    email: false

language: objective-c

before_install:
    - brew update &>brew-update.log
    - brew install gradle &>brew-gradle.log
    
script:
    - gradle build &>build.log

after_script:
    - ls